language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
before_script:
  - sudo apt-get update
  - sudo apt-get install bash zsh
script: 'bin/tf_test test/*/*.rb && bundle exec tf --text test/comment/*_comment_test.sh'
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
